spring:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:sqlite:/home/inigo/code/thermostat/db/thermostat.db

sqlite:
  url: jdbc:sqlite:/home/inigo/code/thermostat/db/thermostat.db
